/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DOVART } from "./DOVART";
export type { ERC20 } from "./ERC20";
export type { ERC721 } from "./ERC721";
export type { TestContact } from "./TestContact";
export * as factories from "./factories";
export { DOVART__factory } from "./factories/DOVART__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC721__factory } from "./factories/ERC721__factory";
export { TestContact__factory } from "./factories/TestContact__factory";
